# Generated by Django 3.0.6 on 2020-05-29 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=256)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('caffeine', models.IntegerField()),
                ('milk', models.IntegerField()),
                ('water', models.IntegerField()),
                ('sugar', models.IntegerField()),
                ('temperature', models.CharField(max_length=256)),
                ('country', models.CharField(max_length=30)),
            ],
        ),
    ]
